apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valuesObject:
        defaultVaultConnection:
          enabled: true
          address: "http://vault.vault.svc.cluster.local:8200"
          skipTLSVerify: false
        controller:
          manager:
            clientCache:
              persistenceModel: direct-encrypted
              storageEncryption:
                enabled: true
                mount: demo-auth-mount
                keyName: vso-client-cache
                transitMount: demo-transit
                kubernetes:
                  role: auth-role-operator
                  serviceAccount: demo-operator
    chart: vault-secrets-operator
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.4.2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault-secrets-operator-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true