apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valuesObject:
        injector:
          enabled: false
        server:
          affinity: ""
          ha:
            enabled: true
            raft: 
              enabled: true
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.27.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true